"""AgentOS Aggregator — the default swap route.

An HTTP API in front of 0x Swap API v2, served at
``https://agg.useagentos.dev``. Every endpoint is a plain ``GET`` and there
is no API key: a quote is one request that comes back with the price *and*
the unsigned calldata, including the ERC-20 approval when one is needed.

The service holds no key and never broadcasts, so reading it cannot move
funds — a swap happens only when this wallet signs the calldata below. Two
facts from that response are checked here before anything is signed:

* the approval's ``spender`` is one of the contracts this desk knows the
  aggregator to use (:data:`TRUSTED_SPENDERS`, 0x's AllowanceHolder) *and*
  the same contract the swap transaction is sent ``to``. The set is pinned
  here, not read from the response: a response that names some other
  address, however consistently, is refused, not signed;
* the approval is for exactly what the order needs — the API never asks for
  an unlimited allowance, so one that does is refused too.

Quotes carry a 30-second ``expiresAt`` generated by the aggregator. We treat
them as fresh for rather less than that (:data:`QUOTE_FRESH_S`) so the
service re-quotes rather than signing calldata that lapses mid-flight.
"""

from __future__ import annotations

import asyncio
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import httpx

from agentos.trading.chains import NATIVE_ADDRESS, ChainSpec, is_native, normalize_address
from agentos.trading.evm import USER_AGENT, EvmClient, is_unlimited
from agentos.trading.providers import (
    PROVIDER_LABELS,
    ProbeResult,
    ProviderError,
    ProviderQuote,
)
from agentos.trading.uniswap import DecisionOrigin

AGGREGATOR_BASE = "https://agg.useagentos.dev"
#: What the aggregator calls the gas coin. Our own native address is the zero
#: address, which the API rejects outright ("the zero address is not a token").
NATIVE_SENTINEL = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
SUPPORTED_CHAIN_IDS: frozenset[int] = frozenset({8453, 4663})
#: A quote is stamped ``now + 30s`` upstream; stop trusting it earlier so the
#: approval-then-swap sequence never reaches the chain with lapsed calldata.
QUOTE_FRESH_S = 20.0
DEFAULT_SLIPPAGE_BPS = 50
MIN_SLIPPAGE_BPS = 1
MAX_SLIPPAGE_BPS = 500
#: 0x's AllowanceHolder — what every approval the aggregator asks for names
#: (seen live on Base 2026-09-20; the same address on every 0x chain). The
#: only spender an approval for this provider may carry, and the only
#: contract a swap that needed an approval may be sent to.
ALLOWANCE_HOLDER = "0x0000000000001ff3684f28c67538d4d072c22734"
TRUSTED_SPENDERS: frozenset[str] = frozenset({ALLOWANCE_HOLDER})

#: The aggregator's error envelope maps onto the engine's own codes. The
#: bool is whether retrying the same request could plausibly work.
_ERROR_CODES: dict[str, tuple[str, bool]] = {
    "INVALID_REQUEST": ("trading.invalid", False),
    "UNKNOWN_TOKEN": ("trading.unknown_token", False),
    "TOKEN_NOT_TRADEABLE": ("trading.token_not_tradeable", False),
    "UNSUPPORTED_CHAIN": ("trading.unsupported_chain", False),
    "SLIPPAGE_OUT_OF_RANGE": ("trading.invalid", False),
    "DECIMALS_UNKNOWN": ("trading.invalid", False),
    "RATE_LIMITED": ("trading.provider", True),
    "UPSTREAM_REJECTED": ("trading.provider", False),
    "UPSTREAM_RATE_LIMITED": ("trading.provider", True),
    "UPSTREAM_ERROR": ("trading.provider", True),
    "MISCONFIGURED": ("trading.provider", False),
    "INTERNAL_ERROR": ("trading.provider", True),
}


class AggregatorError(ProviderError):
    pass


def _f(value: Any) -> float | None:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _raw(value: Any) -> int | None:
    """Read a base-unit integer string; ``raw`` is the authoritative field."""
    if isinstance(value, dict):
        value = value.get("raw")
    if value in (None, ""):
        return None
    try:
        return int(str(value))
    except ValueError:
        return None


def slippage_to_bps(slippage_pct: float | None) -> int:
    """Percent to basis points, inside the range the aggregator accepts."""
    if slippage_pct is None:
        return DEFAULT_SLIPPAGE_BPS
    bps = int(round(float(slippage_pct) * 100))
    return max(MIN_SLIPPAGE_BPS, min(MAX_SLIPPAGE_BPS, bps))


def _expires_at(value: Any) -> float | None:
    """``expiresAt`` is an ISO-8601 instant in UTC; ``None`` when unparseable."""
    text = str(value or "").strip()
    if not text:
        return None
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp()
    except ValueError:
        return None


@dataclass
class AggregatorResponse:
    """One ``/v1/quote`` body, parsed and checked.

    ``transaction`` and ``approval`` are exactly the dicts the aggregator
    sent — the calldata is opaque and is copied byte for byte.
    """

    chain_id: int
    taker: str
    sell_token: dict[str, Any]
    buy_token: dict[str, Any]
    sell_amount_raw: int
    buy_amount_raw: int
    min_buy_amount_raw: int
    slippage_bps: int
    route: list[dict[str, Any]]
    fee: dict[str, Any] | None
    gas_estimate: int | None
    gas_cost_native: float | None
    transaction: dict[str, Any] | None
    approval: dict[str, Any] | None
    expires_at: float | None
    explanation: str
    fetched_at: float
    warnings: list[str] = field(default_factory=list)

    @property
    def spender(self) -> str | None:
        """The spender the response named (already checked against TRUSTED_SPENDERS)."""
        if self.approval:
            return str(self.approval.get("spender") or "").lower() or None
        if self.transaction:
            return str(self.transaction.get("to") or "").lower() or None
        return None

    @property
    def routing(self) -> str:
        """The first-hop sources, folded into a label for the ledger."""
        sources = [str(hop.get("source") or "").strip() for hop in self.route]
        joined = " + ".join(s for s in sources if s)
        return joined or "AGGREGATOR"


class AggregatorClient:
    def __init__(
        self,
        *,
        base_url: str = AGGREGATOR_BASE,
        http: httpx.AsyncClient | None = None,
        timeout: float = 15.0,
        max_retries: int = 2,
        sleep: Callable[[float], Any] | None = None,
    ) -> None:
        self.base_url = (base_url or AGGREGATOR_BASE).rstrip("/")
        self._own_http = http is None
        self._http = http or httpx.AsyncClient(timeout=timeout)
        self._timeout = timeout
        self._max_retries = max(0, int(max_retries))
        self._sleep = sleep or asyncio.sleep

    async def aclose(self) -> None:
        if self._own_http:
            await self._http.aclose()

    @staticmethod
    def chain_param(chain: ChainSpec) -> str:
        if chain.chain_id not in SUPPORTED_CHAIN_IDS:
            raise AggregatorError(
                "trading.unsupported_chain",
                f"The aggregator does not serve {chain.name}",
            )
        return str(chain.chain_id)

    @staticmethod
    def to_token_param(address: str) -> str:
        """Our zero-address native sentinel becomes the aggregator's own."""
        return NATIVE_SENTINEL if is_native(address) else normalize_address(address)

    @staticmethod
    def from_token_param(address: str) -> str:
        if str(address or "").lower() == NATIVE_SENTINEL.lower():
            return NATIVE_ADDRESS
        return normalize_address(address)

    def _headers(self) -> dict[str, str]:
        return {"accept": "application/json", "user-agent": USER_AGENT}

    async def _get(self, path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        url = f"{self.base_url}{path}"
        attempt = 0
        while True:
            try:
                response = await self._http.get(
                    url, params=params, headers=self._headers(), timeout=self._timeout
                )
            except httpx.HTTPError as exc:
                if attempt < self._max_retries:
                    attempt += 1
                    await self._sleep(0.5 * attempt)
                    continue
                raise AggregatorError(
                    "trading.provider", f"Aggregator unreachable: {exc}", retryable=True
                ) from exc
            try:
                body: Any = response.json()
            except ValueError:
                body = None
            if response.status_code >= 400 or (isinstance(body, dict) and "error" in body):
                error = self._error(body, response.status_code)
                # The aggregator's own limiter and 0x's shared budget both say
                # how long to wait. Honour it once rather than hammering.
                if error.retryable and attempt < self._max_retries:
                    attempt += 1
                    delay = _f((error.details or {}).get("retryAfterSeconds")) or 0.5 * attempt
                    await self._sleep(min(delay, 5.0))
                    continue
                raise error
            if not isinstance(body, dict):
                raise AggregatorError("trading.provider", "Aggregator returned no JSON")
            return body

    @staticmethod
    def _error(body: Any, status: int) -> AggregatorError:
        payload = (body or {}).get("error") if isinstance(body, dict) else None
        payload = payload if isinstance(payload, dict) else {}
        upstream = str(payload.get("code") or "").strip().upper()
        message = str(payload.get("message") or "").strip()
        code, retryable = _ERROR_CODES.get(upstream, ("trading.provider", status >= 500))
        details = dict(payload.get("details") or {})
        details["aggregatorCode"] = upstream or f"HTTP_{status}"
        retry_after = payload.get("retryAfterSeconds")
        if retry_after is not None:
            details["retryAfterSeconds"] = retry_after
        return AggregatorError(
            code,
            message or f"Aggregator request failed ({status})",
            retryable=retryable,
            details=details,
        )

    async def health(self) -> dict[str, Any]:
        return await self._get("/health")

    async def quote(
        self,
        *,
        chain: ChainSpec,
        taker: str,
        token_in: str,
        token_out: str,
        amount_raw: int,
        slippage_bps: int,
    ) -> AggregatorResponse:
        body = await self._get(
            "/v1/quote",
            {
                "chain": self.chain_param(chain),
                "sell": self.to_token_param(token_in),
                "buy": self.to_token_param(token_out),
                "sellAmountRaw": str(amount_raw),
                "slippageBps": str(int(slippage_bps)),
                "taker": taker,
            },
        )
        return self._parse_quote(body, chain=chain, taker=taker, amount_raw=amount_raw)

    def _parse_quote(
        self, body: dict[str, Any], *, chain: ChainSpec, taker: str, amount_raw: int
    ) -> AggregatorResponse:
        # "No route right now" is a 200 with every money field nulled out.
        if not body.get("liquidityAvailable", True):
            raise AggregatorError(
                "trading.no_route",
                str(body.get("explanation") or "").strip()
                or "The aggregator found no route for this pair right now",
                retryable=True,
            )
        buy_amount = _raw(body.get("buyAmount"))
        min_buy = _raw(body.get("minBuyAmount"))
        if buy_amount is None or min_buy is None:
            raise AggregatorError("trading.no_route", "Aggregator quote carried no output amount")
        transaction = body.get("transaction")
        if not isinstance(transaction, dict) or not transaction.get("data"):
            raise AggregatorError("trading.tx_failed", "Aggregator quote carried no calldata")
        approval = body.get("approval")
        approval = approval if isinstance(approval, dict) and approval.get("required") else None

        warnings: list[str] = []
        issues = body.get("issues") if isinstance(body.get("issues"), dict) else {}
        balance = issues.get("balance") if isinstance(issues, dict) else None
        if isinstance(balance, dict):
            # Still a 200 with valid calldata; it simply reverts until funded.
            warnings.append("The aggregator reports this wallet cannot cover the sell amount yet.")
        if isinstance(issues, dict) and issues.get("simulationIncomplete"):
            warnings.append("The route could not be fully simulated upstream.")

        gas = body.get("gas") if isinstance(body.get("gas"), dict) else {}
        fee = body.get("fee") if isinstance(body.get("fee"), dict) else None

        parsed = AggregatorResponse(
            chain_id=int(body.get("chainId") or chain.chain_id),
            taker=taker,
            sell_token=dict(body.get("sellToken") or {}),
            buy_token=dict(body.get("buyToken") or {}),
            sell_amount_raw=_raw(body.get("sellAmount")) or amount_raw,
            buy_amount_raw=buy_amount,
            min_buy_amount_raw=min_buy,
            slippage_bps=int(body.get("slippageBps") or DEFAULT_SLIPPAGE_BPS),
            route=[hop for hop in (body.get("route") or []) if isinstance(hop, dict)],
            fee=fee,
            gas_estimate=_raw(gas.get("estimate")) if isinstance(gas, dict) else None,
            gas_cost_native=_f(gas.get("estimatedCostNative")) if isinstance(gas, dict) else None,
            transaction=dict(transaction),
            approval=dict(approval) if approval else None,
            expires_at=_expires_at(body.get("expiresAt")),
            explanation=str(body.get("explanation") or ""),
            fetched_at=time.time(),
            warnings=warnings,
        )
        self._check_approval(parsed)
        return parsed

    @staticmethod
    def _check_approval(parsed: AggregatorResponse) -> None:
        """An approval may only name a pinned spender, and it must be the swap target.

        The aggregator's calldata is opaque, but two things are not. The
        spender has to be one of :data:`TRUSTED_SPENDERS` — a constant of this
        module, never something the response gets to choose, or the check
        would only prove the response agrees with itself. And 0x's
        AllowanceHolder is both the spender and the swap target, so the two
        must match. The amount is bounded too: the API asks for what the
        order needs, so an unlimited allowance is a response we do not sign.
        """
        if parsed.approval is None:
            return
        spender = str(parsed.approval.get("spender") or "").lower()
        target = str((parsed.transaction or {}).get("to") or "").lower()
        if spender not in TRUSTED_SPENDERS:
            raise AggregatorError(
                "trading.tx_failed",
                f"Aggregator approval names spender {spender or '(none)'}, which is not "
                f"a contract this desk trusts ({', '.join(sorted(TRUSTED_SPENDERS))}); "
                "refusing to sign",
            )
        if spender != target:
            raise AggregatorError(
                "trading.tx_failed",
                f"Aggregator approval names spender {spender}, "
                f"but the swap is sent to {target or '(none)'}; refusing to sign",
            )
        tx = parsed.approval.get("transaction")
        if not isinstance(tx, dict) or not tx.get("data"):
            raise AggregatorError(
                "trading.tx_failed", "Aggregator said an approval is required but sent no calldata"
            )
        for amount in (parsed.approval.get("amountNeeded"), _approve_amount(str(tx["data"]))):
            raw = _raw(amount)
            if raw is not None and is_unlimited(raw):
                raise AggregatorError(
                    "trading.tx_failed",
                    "Aggregator asked for an unlimited allowance, which it never needs; "
                    "refusing to sign",
                )

    async def probe(self, *, chain: ChainSpec) -> ProbeResult:
        started = time.monotonic()
        try:
            body = await self.health()
        except ProviderError as exc:
            latency = (time.monotonic() - started) * 1000
            return ProbeResult(ok=False, latency_ms=latency, error=str(exc))
        latency = (time.monotonic() - started) * 1000
        if not body.get("ok"):
            return ProbeResult(ok=False, latency_ms=latency, error="Aggregator reports not ok")
        if not body.get("configured", True):
            return ProbeResult(
                ok=False,
                latency_ms=latency,
                error="Aggregator is deployed without its upstream secrets",
            )
        chains = {int(c) for c in (body.get("chains") or []) if str(c).strip().isdigit()}
        if chains and chain.chain_id not in chains:
            return ProbeResult(
                ok=False, latency_ms=latency, error=f"Aggregator does not serve {chain.name}"
            )
        return ProbeResult(ok=True, latency_ms=latency, error=None)


class AggregatorProvider:
    id = "aggregator"
    label = PROVIDER_LABELS["aggregator"]
    needs_api_key = False

    def __init__(self, client: AggregatorClient) -> None:
        self.client = client

    async def probe(self, *, chain: ChainSpec) -> ProbeResult:
        return await self.client.probe(chain=chain)

    async def quote(
        self,
        *,
        chain: ChainSpec,
        swapper: str,
        token_in: str,
        token_out: str,
        amount_raw: int,
        slippage_pct: float | None,
        decision_origin: DecisionOrigin,
    ) -> ProviderQuote:
        warnings: list[str] = []
        bps = slippage_to_bps(slippage_pct)
        if slippage_pct is not None and bps != int(round(float(slippage_pct) * 100)):
            warnings.append(
                f"Slippage was clamped to {bps / 100:.2f}% — the aggregator accepts "
                f"{MIN_SLIPPAGE_BPS / 100:.2f}%–{MAX_SLIPPAGE_BPS / 100:.2f}%."
            )
        parsed = await self.client.quote(
            chain=chain,
            taker=swapper,
            token_in=token_in,
            token_out=token_out,
            amount_raw=amount_raw,
            slippage_bps=bps,
        )
        return self._to_quote(parsed, chain=chain, swapper=swapper, extra_warnings=warnings)

    def _to_quote(
        self,
        parsed: AggregatorResponse,
        *,
        chain: ChainSpec,
        swapper: str,
        extra_warnings: list[str] | None = None,
    ) -> ProviderQuote:
        # A quote is fresh for the shorter of our own window and the
        # aggregator's own stamp, so a slow clock here cannot outlive it.
        fresh_for = QUOTE_FRESH_S
        if parsed.expires_at is not None:
            fresh_for = min(fresh_for, max(0.0, parsed.expires_at - parsed.fetched_at))
        return ProviderQuote(
            provider=AggregatorProvider.id,
            chain_id=chain.chain_id,
            swapper=swapper,
            token_in=self.client.from_token_param(str(parsed.sell_token.get("address") or "")),
            token_out=self.client.from_token_param(str(parsed.buy_token.get("address") or "")),
            amount_in_raw=parsed.sell_amount_raw,
            amount_out_raw=parsed.buy_amount_raw,
            min_out_raw=parsed.min_buy_amount_raw,
            slippage_pct=parsed.slippage_bps / 100.0,
            # The aggregator publishes no price-impact figure; the service
            # fills it from its own price feed (see TradingService._priced).
            price_impact_pct=None,
            gas_usd=None,
            gas_native=parsed.gas_cost_native,
            quote_id=None,
            routing=parsed.routing,
            fetched_at=parsed.fetched_at,
            fresh_for_s=fresh_for,
            raw=parsed,
            warnings=[*(extra_warnings or []), *parsed.warnings],
        )

    async def approval_tx(
        self, quote: ProviderQuote, *, evm: EvmClient, decision_origin: DecisionOrigin
    ) -> dict[str, Any] | None:
        """The approval the quote already carries — no second round trip.

        ``approval`` is ``None`` when the existing allowance already covers
        this swap, and when the gas coin is being sold.
        """
        if is_native(quote.token_in):
            return None
        parsed: AggregatorResponse = quote.raw
        if parsed.approval is None:
            return None
        tx = dict(parsed.approval.get("transaction") or {})
        return {
            "to": str(tx.get("to") or quote.token_in),
            "from": quote.swapper,
            "data": str(tx.get("data") or ""),
            "value": str(tx.get("value") or "0"),
            "chainId": quote.chain_id,
        }

    def trusted_spenders(self, chain: ChainSpec, quote: ProviderQuote) -> frozenset[str]:
        # Pinned, not read from the quote: what the response names is exactly
        # the thing this set exists to check.
        return TRUSTED_SPENDERS

    def trusted_targets(self, chain: ChainSpec, quote: ProviderQuote) -> frozenset[str]:
        # 0x's AllowanceHolder is the entry point for every route the
        # aggregator builds, ERC-20 and native sells alike; the swap is sent
        # there or not at all.
        return TRUSTED_SPENDERS

    async def build(
        self,
        quote: ProviderQuote,
        *,
        deadline: int,
        sign_permit: Callable[[dict[str, Any]], str] | None,
        decision_origin: DecisionOrigin,
    ) -> dict[str, Any]:
        """The calldata from the quote, re-fetched if it has gone stale.

        The aggregator builds the transaction as part of the quote, so there
        is nothing to sign here: no permit, no second call unless the
        30-second window lapsed while the approval was being mined.
        """
        parsed: AggregatorResponse = quote.raw
        if not quote.fresh:
            parsed = await self.client.quote(
                chain=_chain_for(quote.chain_id),
                taker=quote.swapper,
                token_in=quote.token_in,
                token_out=quote.token_out,
                amount_raw=quote.amount_in_raw,
                slippage_bps=slippage_to_bps(quote.slippage_pct),
            )
            quote.raw = parsed
            quote.amount_out_raw = parsed.buy_amount_raw
            quote.min_out_raw = parsed.min_buy_amount_raw
            quote.fetched_at = parsed.fetched_at
            quote.warnings.extend(parsed.warnings)
        tx_source = parsed.transaction or {}
        tx: dict[str, Any] = {
            "to": str(tx_source.get("to") or ""),
            "from": quote.swapper,
            "data": str(tx_source.get("data") or ""),
            "value": str(tx_source.get("value") or "0"),
            "chainId": quote.chain_id,
        }
        gas = _raw(tx_source.get("gas")) or 0
        if gas > 0:
            tx["gasLimit"] = str(int(gas * 1.2))
        return tx


def _chain_for(chain_id: int) -> ChainSpec:
    from agentos.trading.chains import chain_by_id

    return chain_by_id(chain_id)


def _approve_amount(data: str) -> int | None:
    """The ``uint256`` of an ``approve(address,uint256)`` calldata; None if not one."""
    if not data.startswith("0x095ea7b3") or len(data) != 2 + 8 + 64 + 64:
        return None
    try:
        return int(data[10 + 64 :], 16)
    except ValueError:
        return None


__all__ = [
    "AGGREGATOR_BASE",
    "ALLOWANCE_HOLDER",
    "MAX_SLIPPAGE_BPS",
    "NATIVE_SENTINEL",
    "QUOTE_FRESH_S",
    "TRUSTED_SPENDERS",
    "AggregatorClient",
    "AggregatorError",
    "AggregatorProvider",
    "AggregatorResponse",
    "slippage_to_bps",
]
