"""Mechanical inventory of the legacy control-UI for the React rewrite.

Extracts RPC methods, SPA routes, and web-storage keys from the legacy
vanilla-JS source. Used to seed the parity matrix and, at cutover, to diff
legacy usage against the new frontend (spec §6.3).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

LEGACY_JS = Path(__file__).resolve().parents[1] / "src/agentos/gateway/static/js"

_RPC_CALL = re.compile(r"""\.call\(\s*['"]([a-zA-Z0-9_.]+)['"]""")
_ROUTE = re.compile(r"""Router\.register\(\s*['"]([^'"]+)['"]""")
_STORAGE_CALL = re.compile(
    r"""(?:localStorage|sessionStorage)\.(?:getItem|setItem|removeItem)\(\s*['"]([^'"]+)['"]"""
)
# Fallback: constants like `const WS_URL_KEY = 'agentos.wsUrl';`
_STORAGE_CONST = re.compile(r"""_KEY\s*=\s*['"]([^'"]+)['"]""")


def extract_rpc_methods(js_text: str) -> set[str]:
    return set(_RPC_CALL.findall(js_text))


def extract_routes(js_text: str) -> set[str]:
    return set(_ROUTE.findall(js_text))


def extract_storage_keys(js_text: str) -> set[str]:
    return set(_STORAGE_CALL.findall(js_text)) | set(_STORAGE_CONST.findall(js_text))


def main() -> int:
    methods: dict[str, set[str]] = {}
    routes: set[str] = set()
    keys: dict[str, set[str]] = {}
    for path in sorted(LEGACY_JS.rglob("*.js")):
        text = path.read_text(encoding="utf-8")
        rel = str(path.relative_to(LEGACY_JS.parent.parent))
        for m in extract_rpc_methods(text):
            methods.setdefault(m, set()).add(rel)
        routes |= extract_routes(text)
        for k in extract_storage_keys(text):
            keys.setdefault(k, set()).add(rel)

    print("## Mechanical inventory (generated by scripts/fe_parity_inventory.py)\n")
    print(f"### RPC methods ({len(methods)})\n")
    print("| method | legacy sources |")
    print("| --- | --- |")
    for m in sorted(methods):
        print(f"| `{m}` | {', '.join(sorted(methods[m]))} |")
    print(f"\n### Routes ({len(routes)})\n")
    for r in sorted(routes):
        print(f"- `{r}`")
    print(f"\n### Storage keys ({len(keys)})\n")
    print("| key | legacy sources |")
    print("| --- | --- |")
    for k in sorted(keys):
        print(f"| `{k}` | {', '.join(sorted(keys[k]))} |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
